### ISSUE TITLE
ReflectionError - handle() method does not exist

### ISSUE THREAD

**Issue by hzburki** [irazasyed/larasupport#10]
I am trying to use Vinkla/pusher package with Lumen. I have installed the package and registered it in app.php. However when I run `php artisan vendor:publish` it displays the following error. 

> [ReflectionException]
> Method Irazasyed\Larasupport\Console\VendorPublishCommand::handle() does not exist

Please advice if I'm missing anything

**Comment by devalexandre** [comment]
I have it too :(

 [ReflectionException]                                                               
  Method Irazasyed\Larasupport\Console\VendorPublishCommand::handle() does not exist

**Comment by irazasyed** [comment]
Please install `dev-master` and try? I've updated the command class. It should be fine but please test and confirm. I'll tag this once I know the issue is resolved. Thanks.

**Comment by hzburki** [comment]
I ran the `vendor:publish `command. Works fine now.

**Comment by irazasyed** [comment]
@hzburki Thanks for testing. I've tagged a new release `1.6`.

**Comment by devalexandre** [comment]
work with dev-master :)
