### ISSUE TITLE
Can I use all laravel packages to lumen 

### ISSUE THREAD

**Issue by Gopalkrishna69** [irazasyed/larasupport#14]
Can I use all existing laravel packages to lumen after adding this larasupport package to my lumen 5.7 version? 

If so my lumen package becomes weight, Heard that facing a lot of issues from migrating to laravel from lumen. 
Let me know. Thanks in advance.

**Comment by irazasyed** [comment]
Yes. If you face any issues in general, you can always open an issue ticket.

P.S. Sorry for the delay in responding. Totally missed this ticket.
