### ISSUE TITLE
Class 'Irazasyed\Larasupport\Providers\ArtisanServiceProvider' not found Lumen

### ISSUE THREAD

**Issue by AdrianaTheo** [irazasyed/larasupport#17]
Hello there!
I am using lumen 8.0 microservice to implement an mqtt communication, but when I publish a package
`php artisan vendor:publish --provider="Salman\Mqtt\MqttServiceProvider"` 

it shows me this error: `Class 'Irazasyed\Larasupport\Providers\ArtisanServiceProvider' not found `

I have already added the service provider to bootstrap/app.php file.
$app->register(Irazasyed\Larasupport\Providers\ArtisanServiceProvider::class);

thank you in advance

**Comment by irazasyed** [comment]
Hey!

Can you please try the latest version? I've just pushed with some minor changes.

**Comment by AdrianaTheo** [comment]
Thank you! It works now
