### ISSUE TITLE
Getting issue on compatible with spatie/laravel-newsletter

### ISSUE THREAD

**Issue by kganeshenoah** [irazasyed/larasupport#24]
- **Library Version**: 1.7.0
- **Lumen Version**: 5.8.13
- **PHP Version**: 7.1.33

**Description**  
After updating your library version 1.7.0, Im getting error from laravel newsletter saying below error message.

Call to undefined method Laravel\Lumen\Application::configPath() newsletter

After rollback to your earlier version, It start working fine. Now, I have fixed the version to 1.6.0 to avoid updating your library.

**Steps To Reproduce**  

**Possible Solution**  

**Additional Context**  

<details>
<summary>Logs</summary>

</details>

**Comment by irazasyed** [comment]
Please try this version `v1.7.1`: https://github.com/irazasyed/larasupport/releases/tag/v1.7.1

**Comment by kganeshenoah** [comment]
Great! It's working now. Thanks for the quick support.

**Comment by irazasyed** [comment]
Awesome. Thanks for confirming!
