### ISSUE TITLE
Documentation is not enough, apologies if I am wrong

### ISSUE THREAD

**Issue by themodernpk** [irazasyed/larasupport#26]
**Description**  
I have followed both step:
```
composer require irazasyed/larasupport
```
and 

```
$app->register(Irazasyed\Larasupport\Providers\ArtisanServiceProvider::class);
```

and now I trying to use the following laravel package

https://cartalyst.com/manual/stripe-laravel/13.x 

which requires a `ServiceProvider`, `Facade` to be registered and define `stripe > secret`  variable. How and where to do that? Can you please guide me?

Thanks

**Comment by irazasyed** [comment]
The instructions are given on their docs.

You need to create a new `config/services.php` file and copy/paste the code given on their [page](https://cartalyst.com/manual/stripe-laravel/13.x#set-the-api-key).

Register the service provider and facade in your bootstrap app file in Lumen.

Hope that helps!
