### ISSUE TITLE
Laravel\Lumen\Application::routesAreCached()

### ISSUE THREAD

**Issue by qodeboy** [irazasyed/larasupport#3]
Hello, does this package provides any replacement for routesAreCached() method?

I'm trying to install some Laravel packages on clean Lumen installation, with `larasupport` package installed, but I'm getting this FatalErrorException:

```
[Symfony\Component\Debug\Exception\FatalErrorException]
Call to undefined method Laravel\Lumen\Application::routesAreCached()
```

If no, is there any way I could add it manually?

**Lumen:**
Lumen (5.2.6) (Laravel Components 5.2.*)

**Comment by irazasyed** [comment]
Hi, Nope. This package doesn't provide that.

The only way i can think of is by extending the lumen app class and adding `routesAreCached()` method and then swapping it in bootstrap. It's a work around.

Other than that, maybe ask the package owner to add support for Lumen.
